# To get started with Dependabot version updates, you'll need to specify which
2
# package ecosystems to update and where the package manifests are located.
3
# Please see the documentation for all configuration options:
4
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
5
​
6
version: 2
7
updates:
8
  - package-ecosystem: "" # See documentation for possible values
9
    directory: "/" # Location of package manifests
10
    schedule:
11
      interval: "daily"
12